spring:
  application:
    name: CleanCommerce
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/commerce
    username: postgres
    password: postgres
  jpa:
    hibernate:
      show-sql: true